[project]
name = "cpu-worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pyscrypt>=1.6.2",
    "tierkreis",
]

[tool.uv.sources]
tierkreis = { path = "../../../tierkreis", editable = true }
