#!/usr/bin/env bash
LAUNCHER_DIR=$(dirname "$0")
printf '\n\n------ NTCHEM ------'
INPUT_FILE=$(cat "$1" | jq -r '.inputs.molecular_input')
OUTPUT_FILE=$(cat "$1" | jq -r '.outputs.ntchem_output')
DONE_FILE=$(cat "$1" | jq -r '.done_path')

echo $INPUT_FILE
echo $OUTPUT_FILE

cat $INPUT_FILE

touch $OUTPUT_FILE
echo "dummyntchemoutput" > "$OUTPUT_FILE"

touch $DONE_FILE