name: Reusable setup for command

inputs:
  python_version:
    required: true
  command_name:
    required: true
  command:
    required: true

jobs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up uv & venv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.6"
        enable-cache: true
        python-version: ${{ github.event.inputs.python_version }}
        cache-dependency-glob: uv.lock

    - name: Setup just
      uses: extractions/setup-just@v3

    - name: ${{ github.event.inputs.command_name }}
      run: ${{ github.event.inputs.command }}
