steps:
  name: Lint
  runs-on: ubuntu-24.04
  strategy:
    matrix:
      python-version: ["3.12"]
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: "0"

    - name: Set up uv & venv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true
        python-version: ${{ matrix.python-version }}
        cache-dependency-glob: uv.lock

    - name: Setup just
      uses: extractions/setup-just@v3
