import type { components } from "./api_stubs"; // generated by openapi-typescript

export type WorkflowDisplay = components["schemas"]["WorkflowDisplay"];
export type PyGraph = components["schemas"]["PyGraph"];
export type PyEdge = components["schemas"]["PyEdge"];
export type PyNode = components["schemas"]["PyNode"];
