import type { paths, components } from "./api_stubs"; // generated by openapi-typescript

export type Workflow =
  paths["/api/workflows/"]["get"]["responses"]["200"]["content"]["application/json"][0];
export type PyGraph = components["schemas"]["PyGraph"];
export type PyEdge = components["schemas"]["PyEdge"];
export type PyNode = components["schemas"]["PyNode"];
