[project]
name = "substitution-worker"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.7",
    "pytket>=2.9.3",
    "tierkreis",
]

[tool.uv.sources]
tierkreis = { path = "../../../tierkreis" }
