[project]
name = "examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytket>=2.7.0",
    "tierkreis",
]

[tool.uv.sources]
tierkreis = { path = "../tierkreis", editable = true }
