[project]
name = "nexus-worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "qnexus>=0.10.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
