[project]
name = "aws-batch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "tierkreis",
]

[tool.uv.sources]
tierkreis = { git = "https://github.com/CQCL/tierkreis", subdirectory = "tierkreis", branch = "main" }
