[package]
name = "tierkreis_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
color-eyre = "0.6.3"
crossterm = "0.28.1"
directories = "6.0.0"
glob = "0.3.2"
notify = "8.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
