import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api_stubs"; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.BASE_URL,
  headers: { Accept: "application/json" },
});
export const $api = createClient(fetchClient);
