import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api_stubs"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.BASE_URL,
  headers: { Accept: "application/json" },
});
const $api = createClient(fetchClient);

export const fetchLogs = async (workflow_id: string) => {
  const res = await fetchClient.GET("/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
    parseAs: "text",
  });
  return res.data ?? "No logs.";
};

export const fetchErrors = async (
  workflow_id: string,
  node_location_str: string
) => {
  const params = { path: { workflow_id, node_location_str } };
  const res = await fetchClient.GET(
    "/api/workflows/{workflow_id}/nodes/{node_location_str}/errors",
    { params, parseAs: "text" }
  );
  return res.data ?? "No errors.";
};

export const listWorkflowsQuery = () => $api.useQuery("get", "/api/workflows/");
export const logsQuery = (workflow_id: string) =>
  $api.useQuery("get", "/api/workflows/{workflow_id}/logs", {
    params: { path: { workflow_id } },
  });
export const nodeQuery = (workflow_id: string, node_location_str: string) =>
  $api.useQuery(
    "get",
    "/api/workflows/{workflow_id}/nodes/{node_location_str}",
    { params: { path: { workflow_id, node_location_str } } }
  ).data;
