import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api_stubs"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: import.meta.env.BASE_URL + "api/",
});
export const $api = createClient(fetchClient);
