name: Python package CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  UV_VERSION: "0.6.6"

jobs:
  lint:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Setup action
        uses: ./.github/actions/setup

      - name: Lint project
        run: |
          just lint

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Setup action
        uses: ./.github/actions/setup

      - name: Test project
        run: |
          just test

  examples:
    name: examples
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Setup action
        uses: ./.github/actions/setup

      - name: Check examples do not error
        run: |
          just examples

  docs:
    name: docs
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Setup action
        uses: ./.github/actions/setup

      - name: Check docs do not error
        run: |
          just docs
