name: Python package CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup action
        uses: ./.github/actions/setup

      - name: Lint project
        run: |
          just lint

  test:
    name: test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup action
        uses: ./.github/actions/setup

      - name: Test project
        run: |
          just test

  examples:
    name: examples
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup action
        uses: ./.github/actions/setup

      - name: Check examples do not error
        run: |
          just examples

  docs:
    name: docs
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup action
        uses: ./.github/actions/setup

      - name: Check docs do not error
        run: |
          just docs
