name: Python package CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  UV_VERSION: "0.6.6"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up uv & venv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Lint project
        run: |
          just lint

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up uv & venv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Lint project
        run: |
          just test

      - name: Upload pytest test results
        uses: actions/upload-artifact@master
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: htmlcov/
