name: Build and publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build docs.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python '3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: "pip"
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Install Tierkreis
        run: pip install '.[typecheck,docs]'
      - name: Build docs
        run: |
          cd docs
          ./build.sh
      - name: Upload artifact.
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/build/

  publish:
    name: Publish docs.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages.
        id: deployment
        uses: actions/deploy-pages@v4