on:
  release:
    types: [created]
  workflow_dispatch:
  push:

jobs:
  docs:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv & venv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Build docs
        run: just docs

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
