on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - name: Build docs
        uses: ./.github/workflows/run-command.yml
        with:
          command_name: docs
          command: just docs

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
