name: Merge to main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: ./.github/actions/setup_deps
        with:
          command_name: docs
          command: just docs
          deploy_docs: "yes"

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
