on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload all packages to PyPI
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Build frontend assets
        uses: ./.github/workflows/run-command.yml
        with:
          command_name: prod
          command: just prod

      - name: Build package
        run: |
          uv build --all-packages

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
