name: Release

on:
  workflow_dispatch:
  release:
    types: [created]
  push:

jobs:
  release:
    permissions:
      id-token: write

    uses: ./.github/workflows/run-command.yml
    with:
      command_name: release
      command: just prod && uv build --all-packages
      publish_pypi: "yes"
