on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    strategy:
      matrix:
        package-directory:
          - tierkreis
          - tierkreis_visualization
        python-version: ['3.12']
    defaults:
      run:
        working-directory: ${{ matrix.package-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up uv & venv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock

      - name: Build package
        run: |
          uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
