name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up deps
        uses: ./.github/actions/setup_deps
        with:
          include_node: "yes"

      - name: Build frontend
        run: just prod

      - name: Build Python package
        run: uv build --all-packages

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
