name: Reusable setup for command

on:
  workflow_call:
    inputs:
      command_name:
        required: true
        type: string
      command:
        required: true
        type: string
      deploy_docs:
        type: string
        default: "no"
      publish_pypi:
        type: string
        default: "no"

jobs:
  run:
    name: ${{ inputs.command_name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv & venv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: uv.lock

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: ${{ inputs.command_name }}
        run: ${{ inputs.command }}
        if: (matrix.python-version == matrix.python-version.last)

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        if: (inputs.deploy_docs == 'yes') && (matrix.python-version == matrix.python-version.last)
        with:
          path: docs/build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: (inputs.deploy_docs == 'yes') && (matrix.python-version == matrix.python-version.last)

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: (inputs.publish_pypi == 'yes') && (matrix.python-version == matrix.python-version.last)
