name: Reusable setup for command

on:
  workflow_call:
    inputs:
      command_name:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  run:
    name: ${{ inputs.command_name }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup deps
        uses: ./.github/actions/setup_deps
        with:
          python_version: ${{ matrix.python-version }}

      - name: Install with uv
        run: uv sync --all-groups

      - name: ${{ inputs.command_name }}
        run: ${{ inputs.command }}
