#!/usr/bin/env bash
# usage run_with_server <server-binary> <config-file> <command ...>
set -e # exit+fail if any command fails

rm -f _server_output.txt
touch _server_output.txt
$1 -C $2 >>_server_output.txt 2>&1 &
tail -f _server_output.txt | grep --line-buffered "Server started" | (head -n1 && killall tail)
bash -c "${*:3}" # This does not do any further expansion
kill -INT %1
